### ISSUE TITLE
数字键盘中，怎么长按删除

### ISSUE THREAD

**Issue by kolvs** [onlyloveyd/LazyKeyboard#1]
数字键盘中，没有长按删除功能

**Comment by onlyloveyd** [comment]
@assess15 
代码已修复，下个版本会体现。谢谢反馈
[e806583c549b8fa1fd6dbcff6beca913d55681fa](https://github.com/onlyloveyd/LazyKeyboard/commit/e806583c549b8fa1fd6dbcff6beca913d55681fa)
