### ISSUE TITLE
键盘点击预览

### ISSUE THREAD

**Issue by rcj60560** [onlyloveyd/LazyKeyboard#3]
你好 @onlyloveyd  我在自定义键盘里面添加了一个keyPreviewLayout ，keyPreviewHeight，
然后点击的时候报错
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@cb81edb is not valid; is your activity running?
是不是这样的popupwindow这样的形式不能预览吗？

**Comment by onlyloveyd** [comment]
具体测试程序发我一份，我看下你怎么用的

**Comment by rcj60560** [comment]
我的意思就是 参考安卓系统键盘 不是有个点击字母的时候有个橘色的预览吗 您代码里面 没有这个功能。

**Comment by onlyloveyd** [comment]
确实没有这个功能

**Comment by rcj60560** [comment]
@onlyloveyd  能添加一下这个功能吗 想看看怎么实现的

**Comment by onlyloveyd** [comment]
@rcj60560 暂无计划
